Capstone Project
arnoldnekemiah/Developer-school pull request #3
Opened 2023-05-23 19:10 UTC by arnoldnekemiah

I made the website using Mobile first approach
After I made the desktop version
Then created the Speakers section dynamically as required, and also made the Hamburger menu.
COnfihured Linters

2023-05-24 05:50 UTC, divinecharlotte requested changes
Hi @arnoldnekemiah       , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- linters are passing 👍 
- Descriptive Pr 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [ ] kindly consider adding a working link to your Live demo section  to give a good user experience to the people visiting your readme while deploying your app put into consideration the below 

1. The student makes use of GitHub Pages to deploy the web pages.
2. The project is deployed properly, all pages, links, and images work as expected.
3. A link to the deployed project is present in the README.
before requesting for another review
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 05:50 UTC, divinecharlotte commented on index.html
>      <script src="main.js"></script>
- [ ] Kindly consider adding a footer on this page on the desktop version cause currently  on the mobile version its okay no need to display it but on the desktop make sure you add it to make your page look exactly as the given design
- check how it  should look 
<img width="657" alt="Screen Shot 2023-05-24 at 07 20 42" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/b4739aee-6ef7-41b4-8aaa-ac02bbf6497b">

2023-05-24 05:50 UTC, divinecharlotte commented on about.html
> +            </ul>
- [ ] kindly consider making sure that this list-items stick to the design provided to make your work an exact duplicate of the provided design
check the images below and fix your design 

- your design 👇 
<img width="1425" alt="Screen Shot 2023-05-24 at 07 16 03" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/049f07f1-bf1b-4bc6-a68e-a2a67d2291c4">

- given design 👇 
<img width="874" alt="Screen Shot 2023-05-24 at 07 16 56" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/1756ad2a-4983-4d7f-8101-bb721852c4b0">

2023-05-24 05:50 UTC, divinecharlotte commented on index.html
>          <img class="hello-img" src="./images/hero_img.png" alt="">
- [ ] kindly consider adding this heading as a text not an image for semantic reasons and after doing so make sure that it's displayed on same line as a block of text under it to follow the provided design

2023-05-24 05:50 UTC, divinecharlotte commented on main.js
> +  `;
- [ ] on desktop version Kindly consider displaying 3 speakers in each column to make your design an exact duplicate of the given one while doing so make sure you include the small grey line under the red subtitle check also on the attached image and make that text italic to make your design a top-notch
- 
<img width="1439" alt="Screen Shot 2023-05-24 at 07 30 12" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/415514c5-d514-4465-8f68-93e5b2aab960">

2023-05-24 05:50 UTC, divinecharlotte commented on about.html
> +            <div class="contact">
- [ ] kindly consider giving this div the same background color as the one in the given design to make it match the design provided on both screensize

2023-05-24 05:50 UTC, divinecharlotte commented on about.html
> +    </section>
- [ ] kindly consider sticking to the given design as much as possible to deliver what is expected so concerning this section make sure you update it for your design to meet the given ones as am showing you in the images below
- your design 👇 
<img width="1439" alt="Screen Shot 2023-05-24 at 07 45 46" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/cfffe7ec-f49f-4253-bc89-8b8394a6edb1">

- given design 👇 
<img width="870" alt="Screen Shot 2023-05-24 at 07 46 19" src="https://github.com/arnoldnekemiah/Developer-school/assets/60146030/1a26110e-2a41-4645-a4ed-de30719bb929">
 ☠️ make sure you customize your contents as requested in the project requirements

2023-05-24 12:17 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

# Hi @arnoldnekemiah 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
- All linter checks are passing ✔
- Descriptive PR title ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- You just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 12:17 UTC, AbelG101 commented on index.html
>          <img class="hello-img" src="./images/hero_img.png" alt="">
https://github.com/arnoldnekemiah/Developer-school/blob/1d5d96f87bf9f8d0a408173a4340675d3c0c282b/index.html#L42
- [ ] As suggested by the previous reviewer kindly make sure you use the proper heading text instead of an image here as this will make it more optimized and trackable for search engines and it's semantically incorrect to replace text with an image.

2023-05-24 12:17 UTC, AbelG101 commented on about.html
> +            </div>
- [ ] Once again, as mentioned previously you seem to be missing one section below the "contact us" text as shown below in the original design. So please make sure to add it. ✔
- Original design:
  ![image](https://github.com/arnoldnekemiah/Developer-school/assets/104968236/3fb7d657-e754-4393-96a1-1d3252508c74)
- Your design:
 ![image](https://github.com/arnoldnekemiah/Developer-school/assets/104968236/a984d21f-cc5a-4115-81aa-3b9d2f83265a)

2023-05-24 15:05 UTC, OyePriscilla requested changes
Hi @arnoldnekemiah 👍 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented two html pages ✔️ 
Implement one of the sections dynamically with `js` ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 15:05 UTC, OyePriscilla commented on about.html
> +        </div>
- [ ] You've really done well by adding the required section requested by the previou reviewer, but can you please design it according to the given template. 👍 

## Your Design
<img width="929" alt="Untitled" src="https://github.com/arnoldnekemiah/Developer-school/assets/103386183/c27beec2-aa4b-4b47-821c-feab2708d376">

## Given Design
<img width="402" alt="Untitled" src="https://github.com/arnoldnekemiah/Developer-school/assets/103386183/e31b388a-fb68-4035-bbdd-bb4802f7c3bd">

2023-05-24 16:16 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @arnoldnekemiah, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] **[OPTIONAL]** You did a great job working on the suggestions made by previous reviewers! 💯 However, I'm sorry the previous reviewer didn't notice that a visual bug got introduced to the About page navigation bar:

![Screenshot from 2023-05-24 11-11-25](https://github.com/arnoldnekemiah/Developer-school/assets/77069011/74c2fefd-ca7c-421e-b3e4-59d6f1994b09)

I highly recommend correcting it, since having an attractive UI will be very beneficial later on when you start job searching! 🤓 🔧 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 17:05 UTC, merged

2023-05-29 12:55 UTC, ichala commented
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Project Already Approved ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._